version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cmp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Baranov533!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    depends_on:
      - postgres

  cmp-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/investdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Baranov533!
    depends_on:
      - postgres

volumes:
  postgres_data: