CREATE TABLE IF NOT EXISTS users (
    chat_id BIGINT PRIMARY KEY,
    username VARCHAR,
    first_name VARCHAR,
    last_name VARCHAR,
    bot_state VARCHAR
);

CREATE TABLE IF NOT EXISTS applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT,
    territory VARCHAR,
    square VARCHAR,
    image VARCHAR,
    start_work VARCHAR,
    created TIMESTAMP,
    description_work VARCHAR,
    description_object VARCHAR,
    status VARCHAR,
    contact VARCHAR
    );